# Generated by Django 4.2 on 2023-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pepper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("permission", models.IntegerField(default=1)),
                ("token", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
